// *************************************************************************************************
// Horde3D Visual Debugger
//
// Axel Habermaier
// Bachelor Thesis, University of Augsburg, 2008/2009
// *************************************************************************************************
//
// This file was generated by the Code Generator tool on {genTime}. 
// All modifications made in this file will get lost when the code is regenerated by the tool.
// *************************************************************************************************

#define DLL extern "C" __declspec(dllexport)
#define WIN32_LEAN_AND_MEAN

#include <Windows.h>

// ********************* Horde3D Header File ******************************//
{headerFile}
// ******************* End: Horde3D Header File ***************************//

#include <vcclr.h>
#include <string>
#include "Horde3DProxyHandler.h"

using namespace std;
using namespace System;
using namespace Infrastructure::Core::Server;

namespace Horde3D
{
	// Global instance
	NativeProxyHandler g_proxyHandler;

	// Function Pointer Typedefs
{funcPtrTypeDefs}
	
	class Horde3DProxyBase
	{	
	public:
		void Initialize(HINSTANCE dll)
		{			
			// Function Pointer Initialization
{funcPtrInit}
		}
		

		Horde3DProxyBase()
		{
		}
		
		virtual ~Horde3DProxyBase() 
		{
		}

		// Virtual functions
{virtualFuncProxies}
		
	protected:
		// Function Pointer Definitions
{funcPtrDefs}
	};

	class Horde3DProfilingProxy : public Horde3DProxyBase
	{
	private:
		gcroot<System::Diagnostics::Stopwatch^> stopwatch;

	public:
		virtual ~Horde3DProfilingProxy() 
		{
			stopwatch->Stop();
			stopwatch = nullptr;
		}

		Horde3DProfilingProxy()
		{
			stopwatch = gcnew System::Diagnostics::Stopwatch();
			stopwatch->Start();
		}

		// Horde3D Profiling Function Proxies
{profilingFuncProxies}
	};

	class Horde3DNoProfilingProxy : public Horde3DProxyBase
	{
	public:
		virtual ~Horde3DNoProfilingProxy() 
		{
		}

		// Horde3D No Profiling Function Proxies
{noProfilingFuncProxies}
	};

{funcProxies}
}